.Dd March 5, 2016 
.Dt FWBUG1 6
.Os
.Sh NAME
.Nm fwbug1
.Nd a presentation on the Dreamcast and NetBSD
.Sh SYNOPSIS
.Nm
.Op slide-number
.Sh DESCRIPTION
A presentation on how to build, customize, and
run NetBSD on the SEGA Dreamcast, because "Of course it runs NetBSD". 
.Pp
Use arrow keys to navigate slides.
Press
.Dq t
for table of contents.
Press
.Dq q
to quit.

